### ISSUE TITLE
add dependencies to <plugin> section in Usage

### ISSUE THREAD

**Issue by hello-earth-gh** [anomen-s/maven-jaxrpc-plugin#4]
thanks for the plugin.

it is just that I found that I had to add additional section inside the <plugin> with java compiler dependency (according to here: https://stackoverflow.com/questions/34713222/wrapping-ant-in-maven-java-home-points-to-the-jre-but-works-with-just-ant)

                <dependencies>
                    <dependency>
                        <groupId>com.sun</groupId>
                        <artifactId>tools</artifactId>
                        <version>1.5.0</version>
                        <scope>system</scope>
                        <systemPath>${java.home}/../lib/tools.jar</systemPath>
                    </dependency>
                </dependencies>

**Comment by anomen-s** [comment]
thanks for report. I haven't used the plugin for quite a long time but it looks valid.
